name: fifth CICD pipeline practice test
run-name: Deployment by @${{ github.actor }}

on:
    push: 
        branches: [ 'main' ]

jobs:
    build_1: 
        strategy:
            matrix:
                os: [ 'macos-latest', 'windows-latest', 'ubuntu-latest' ]
            max-parallel: 3
            fail-fast: false
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - name: running multiple os in build_1 job...
              run: echo "hello boss, build_1 pratice test is successful"
    
    build_2:
        needs: build_1
        strategy:
            matrix: 
                os: [ 'macos-latest', 'windows-latest', 'ubuntu-latest' ]
            max-parallel: 3
            fail-fast: false
        runs-on: ${{ matrix.os }}
        steps: 
            - uses: actions/checkout@v4
            - name: running multiple os in build_2 job..
              run: echo "hello boss, build_2 practice test is successful"

    build_3:
        needs: [ 'build_2' ]
        strategy: 
            matrix:
                os: [ 'macos-latest', 'windows-latest', 'ubuntu-latest' ]
            max-parallel: 3
            fail-fast: false
        runs-on: ${{ matrix.os }}
        steps: 
            - uses: actions/checkout@v4
            - name: running multiple os in build_3 job...
              run: echo "hello boss, build_3 practice test is successful"
    
    build_4:
        needs: [ 'build_1', 'build_2', 'build_3' ]
        strategy:
            matrix:
                os: [ 'macos-latest', 'windows-latest', 'ubuntu-latest' ]
            max-parallel: 3
            fail-fast: false
        runs-on: ${{ matrix.os }}
        steps: 
            - uses: actions/checkout@v4
            - name: running multiple os in build_4 job...
              run: echo "hello boss, build_4 practice test is successful"