name: fifth CICD pipeline practice test
run-name: deployment practice test by @${{ github.actor }}

on:
    push:
        branches: [ 'main' ]

jobs:
    build_1:
        strategy:
            matrix: 
                os: [ 'macos-latest', 'widnows-latest', 'ubuntu-latest' ]
            max-parallel: 3
            fail-fast: false
        runs-on: ${{ matrix.os }}
        steps: 
            - uses: actions/checkout@v4
            - name: running build_1 test practice
              run: echo "hello boss build_1 test practice successful"
    
    build_2: 
        needs: build_1
        strategy:
            matrix:
                os: [ 'maco-latest', 'windows-latest', 'ubuntu-latest' ]
            max-parallel: 3
            fail-fast: false
        runs-on: ${{ matrix.os }}
        steps: 
            - uses: actions/checkout@v4
            - name: running build_2 test practice
              run: echo "hello boss build_2 test practice successful"
    build_3: 
        needs: [ build_1, build_2 ]
        strategy: 
            matrix:
                os: ['macos-latest', 'windows-latest', 'ubuntu-latest' ]
            max-parallel: 3
            fail-fast: false
        runs-on: ${{ matrix.os }}
        steps: 
            - name: running build_3 test practice
              run: echo "hello boss build_3 test practice successful"