name: CI secwf pipeline
run-name: deploy by @${{ github.actor }}

on: 
    push:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: run an one-line script
              run: echo hello world!

            - name: run a multi-line script
              run: | 
                echo helojkfnslfheirufnlkjfhweoriu,
                echo fjfheroufhrelgjkrngiuerh
    
    build_2:
        runs-on: ubuntu-latest
        steps: 
            - name: run an one-line script build2
              run: echo hello kjshuerhiour!

    build_3:
        runs-on: windows-latest
        steps: 
            - name: run an one-line script sjfbaskyfsu
              run: echo jahsdfiuyerfjksfnuygrak