name: CI secwf pipeline
run-name: deploy by @${{ github.actor }}

on: 
    push:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: run an one-line script
              run: echo hello world!

            - name: run a multi-line script
              run: | 
                echo helojkfnslfheirufnlkjfhweoriu,
                echo fjfheroufhrelgjkrngiuerh