name: Thrid CI Pipeline
run-name: deploy by @${{ github.actor }}

on:
    push:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            - name: Run a one-line script on ubuntu-latest
              run: echo hello world!
    
    build_2:
        needs: build
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run a one-line script on windows-latest
              run: echo hello boss
    
    build_3:
        needs: build_2
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run a one-line script on macos-latest
              run: echo hello boss

    build_multi:
        needs: [build, build_2, build_3]
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
            max-parallel: 3
            fail-fast: false
        runs-on: ${{ matrix.os }}
        steps: 
            - uses: actions/checkout@v4
            - name: run a one-line command on multiple os
              run: echo hello boss CI pipeline is successfully executed!!!!!